version: '3'
services:
  web:
    build:
      context: .
    env_file:
      - ./app/.env
    expose:
      - ${EXPOSE_PORT}
    ports:
      - "${MAP_PORT}:${EXPOSE_PORT}"
    command: npm start
  db:
    image: mysql
    restart: always
    env_file:
      - ./app/.env